language: node_js
node_js:
- 6.9.0
install:
  - npm i -g npm@3
  - npm install
script:
  - npm run eslint
  - npm run test
before_deploy:
  - curl -L https://clis.ng.bluemix.net/download/bluemix-cli/0.6.6/osx | sh
  - chmod -R u+x ./Bluemix_CLI/bin
  # - ./Bluemix_CLI/bin/bluemix plugin install container-registry -r Bluemix
  - chmod +x ./deploy.sh
cache:
  directories:
  - node_modules
deploy:
  provider: script
  script: ./deploy.sh
  on:
    repo: IBM/deploy-react-kubernetes
    branch: deploy
