language: node_js
node_js:
- 6.9.0
install:
  - npm i -g npm@3
  - npm install
script:
  - npm run eslint
  - npm run test
cache:
  directories:
  - node_modules
before_deploy:
  - curl -L https://clis.ng.bluemix.net/download/bluemix-cli/0.6.1/linux64 | tar -zx
  - chmod -R u+x ./Bluemix_CLI/bin
  - ./Bluemix_CLI/bin/bluemix plugin install container-registry -r Bluemix
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - chmod +x ./deploy.sh
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: deploy
